name: auto update files teacher gave us

on:
  schedule:
    - cron: 0 5,14,17 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  sync:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      RCLONE_CONF_TEXT: ${{ secrets.RCLONE_CONF_TEXT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: Alper-Celik

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: activate environment
        uses: HatsuneMiku3939/direnv-action@v1

      - name: download archive
        run: ./get-files.py

      - name: extract archive and upload files
        run: ./extract-and-upload.sh
