name: auto update files teacher gave us

on:
  schedule:
    - cron: 0 5,14,17 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  sync:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    env:
      RCLONE_CONF_TEXT: ${{ secrets.RCLONE_CONF_TEXT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: activate environment
        uses: HatsuneMiku3939/direnv-action@v1

      - name: sync
        run: python .
